FROM apache/spark:3.5.1 AS spark-source

FROM apache/airflow:2.7.1

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jre-headless curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV SPARK_VERSION=3.5.1
ENV SPARK_HOME=/opt/spark-3.5.1-bin-hadoop3
ENV PATH=$PATH:$SPARK_HOME/bin
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

COPY --from=spark-source /opt/spark $SPARK_HOME

RUN mkdir -p /opt/airflow/jars && \
    curl -L -o /opt/airflow/jars/spark-sql-kafka.jar https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.1/spark-sql-kafka-0-10_2.12-3.5.1.jar && \
    curl -L -o /opt/airflow/jars/kafka-clients.jar https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar && \
    curl -L -o /opt/airflow/jars/clickhouse-jdbc.jar https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2/clickhouse-jdbc-0.3.2-all.jar && \
    curl -L -o /opt/airflow/jars/hadoop-aws.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -L -o /opt/airflow/jars/aws-java-sdk-bundle.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar && \
    curl -L -o /opt/airflow/jars/commons-pool2.jar https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar && \
    curl -L -o /opt/airflow/jars/spark-token-provider-kafka.jar https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar

RUN chown -R airflow: /opt/airflow/jars

RUN mkdir -p /opt/spark/work-dir && chown -R airflow: /opt/spark/work-dir
COPY --chown=airflow:root airflow/dags/ /opt/airflow/dags/
COPY --chown=airflow:root spark_consumer/ /opt/spark/work-dir/spark_consumer/
COPY --chown=airflow:root ingest/ /opt/spark/work-dir/ingest/

USER airflow
RUN pip install --no-cache-dir kafka-python requests confluent-kafka pyspark==${SPARK_VERSION} \
    minio openpyxl pandas
