apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: marketing
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  _AIRFLOW_WWW_USER_PASSWORD: password123
  SUPERSET_SECRET_KEY: marketing_big_data_key_2026
