apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: marketing
type: Opaque
stringData:
  CLICKHOUSE_USER: admin
  CLICKHOUSE_PASSWORD: password123
  CLICKHOUSE_DB: marketing_db
