apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: marketing
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:13
          command: ["sh", "-c", "until pg_isready -h postgres -U airflow; do sleep 2; done"]
      containers:
        - name: airflow-init
          image: apache/airflow:2.7.1
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
          command:
            - /bin/bash
            - -c
            - |
              pip install confluent-kafka requests --quiet &&
              airflow db migrate &&
              airflow users create \
                --username admin --firstname Admin --lastname User \
                --role Admin --email admin@example.com \
                --password password123 || true
              echo "Airflow initialized."
