apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: marketing
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: minio-init
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              until mc config host add myminio http://minio:9000 admin password123; do
                echo "Waiting for MinIO..." && sleep 2
              done
              mc mb --ignore-existing myminio/marketing-datalake
              mc anonymous set public myminio/marketing-datalake
              echo "MinIO bucket initialized."
