apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
  namespace: marketing
data:
  ADMIN_USERNAME: admin
  ADMIN_EMAIL: admin@fab.org
  ADMIN_FIRSTNAME: Superset
  ADMIN_LASTNAME: Admin
  SQLALCHEMY_DATABASE_URI: sqlite:////opt/superset/data/superset.db
