apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: marketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
          envFrom:
            - secretRef:
                name: clickhouse-secret
            - configMapRef:
                name: clickhouse-config
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-storage
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse-pvc
