apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: marketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 9092
              name: external
            - containerPort: 29092
              name: internal
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
