apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: marketing
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort
