apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: marketing
spec:
  selector:
    app: kafka
  ports:
    - name: external
      port: 9092
      targetPort: 9092
      nodePort: 30092
    - name: internal
      port: 29092
      targetPort: 29092
  type: NodePort
