apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: marketing
spec:
  selector:
    app: spark-master
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30081
    - name: master
      port: 7077
      targetPort: 7077
  type: NodePort
